###Loading Dataset

In [ ]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
#load dataset
iris= datasets.load_iris()





### Standardization of Data

In [ ]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
#load dataset
iris= datasets.load_iris()


x =iris.data
y=iris.target

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.33)#split the data

std_slc = StandardScaler()
std_slc.fit(x_train)
x_train_std=std_slc.transform(x_train)
x_test_std=std_slc.transform(x_test)

print(x_train[0:5])
print(x_train_std[0:5])
print(x_test[0:5])
print(x_test_std[0:5])





[[4.8 3.4 1.9 0.2]
 [6.1 2.8 4.  1.3]
 [5.8 2.6 4.  1.2]
 [6.  2.2 4.  1. ]
 [5.4 3.9 1.7 0.4]]
[[-1.25973936  0.79114124 -1.09592723 -1.35455693]
 [ 0.34581081 -0.58875627  0.15282328  0.12804269]
 [-0.02470077 -1.0487221   0.15282328 -0.00673909]
 [ 0.22230695 -1.96865377  0.15282328 -0.27630266]
 [-0.51871621  1.94105582 -1.21485585 -1.08499336]]
[[5.7 2.6 3.5 1. ]
 [5.  2.3 3.3 1. ]
 [5.4 3.  4.5 1.5]
 [6.7 3.3 5.7 2.1]
 [7.3 2.9 6.3 1.8]]
[[-0.14820463 -1.0487221  -0.14449827 -0.27630266]
 [-1.01273164 -1.73867086 -0.26342689 -0.27630266]
 [-0.51871621 -0.12879043  0.45014482  0.39760626]
 [ 1.08683396  0.56115832  1.16371654  1.20629697]
 [ 1.82785711 -0.35877335  1.5205024   0.80195161]]



### Label Encoder, One hot Encoder

In [ ]:
species=list(iris.target_names)

from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
l=label_encoder.fit_transform(species)

print(l)

[0 1 2]


In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

### Categorical data to be converted to numeric data
colors = (["red", "green", "yellow", "red", "blue"])

### integer mapping using LabelEncoder
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(colors)
print(integer_encoded)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)

### One hot encoding
onehot_encoder = OneHotEncoder(sparse=False)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)

print(onehot_encoded)

[2 1 3 2 0]
[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
